name: Terraform Validate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Init
        working-directory: environments/dev
        run: terraform init -backend=false

      - name: Validate
        working-directory: environments/dev
        run: terraform validate